{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f0db0f1f-7e73-416d-b092-764d313b2707",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ans1\n",
    "# Exception handling\n",
    "\n",
    "# Exception:\n",
    "\"\"\"\n",
    "Exception basically a runtime error occurred during tht execution of program\n",
    "Exception is the base class for all the exceptions in Python\n",
    "Exceptions are raised when the program is syntactically correct, but the code resulted in an error.\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "# Difference between the Exception and the Syntax error in python \n",
    "\n",
    "\"\"\"\n",
    "1 An Exception in Python is an error that occurs during the execution of a program.  \n",
    "2  Generally Exceptions  are raised when  there is a logical  errors or a certain condtions fails in the program \n",
    "3 exceptions are raised during the execution of the code.\n",
    "\n",
    "Exception handling can be handled using the :\n",
    "try \n",
    "except\n",
    "else\n",
    "finally \n",
    "\"\"\"\n",
    "\n",
    "# Syntax Error:\n",
    "\n",
    "\"\"\"\n",
    "1 syntax errors is that syntax errors occur due to incorrect syntax in the code and are detected by the Python interpreter before the code is executed.\n",
    "2 Syntax errors can be fixed by correcting the syntax in the code \n",
    "3 Syntax errors are detected by the Python interpreter before the code is executed .\n",
    "for example : writing the print wrongly\n",
    "\"\"\"\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ac5c87ad-2d9a-4fe3-8a08-f6058fea223a",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 9\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[38;5;66;03m# for Example\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;66;03m# Without handlig the error\u001b[39;00m\n\u001b[1;32m      8\u001b[0m age \u001b[38;5;241m=\u001b[39m\u001b[38;5;241m10\u001b[39m\n\u001b[0;32m----> 9\u001b[0m result \u001b[38;5;241m=\u001b[39m\u001b[43mage\u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m\n\u001b[1;32m     10\u001b[0m \u001b[38;5;28mprint\u001b[39m(a)\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "# Ans2\n",
    "\"\"\"\n",
    "When an Exception is not handled  then execution of code terminate abnormally. it means\n",
    "code i;e your program terminate abruptly \"\"\"\n",
    "\n",
    "# for Example\n",
    "# Without handlig the error\n",
    "\n",
    "age =10\n",
    "result =age/0   \n",
    "# due to this logical error that error called an excpetion occurrred  so  we need to handle this situation using  the exception handling \n",
    "print(a)\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "6b5bd40b-0c51-4343-b128-cfbde5dd63d5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "this is my except block  [Errno 2] No such file or directory: 'pwsachin.txt'\n"
     ]
    }
   ],
   "source": [
    "# Ans3\n",
    "# Try and Except Statement â€“ Catching Exceptions\n",
    "\"\"\"\n",
    "Try and except statements are used to catch and handle exceptions in Python. \n",
    "\"\"\"\n",
    "# try\n",
    "\"\"\"\n",
    "Statements that can raise exceptions are kept inside the try block\n",
    "\"\"\"\n",
    "# except\n",
    "\"\"\"\n",
    "the statements that handle the exception are written inside except block.\n",
    "\n",
    "\"\"\"\n",
    "\n",
    "# for example\n",
    "import logging  \n",
    "\n",
    "try :  # uisng the try\n",
    "    \n",
    "    logging.basicConfig(filename = \"12feb.log\" , level =logging.DEBUG , format = '%(asctime)s %(message)s' )  #using the logging\n",
    "    f= open(\"pwsachin.txt\" , 'r')\n",
    "    logging.info(\" code that may raise the exception \")\n",
    "    \n",
    "except Exception  as e : \n",
    "    \n",
    "    logging.info(\" error handled in this except block \")\n",
    "    print(\"this is my except block \" , e)\n",
    "    \n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "6491cc2f-f5c7-42cf-9db7-7d16c913eb21",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.6666666666666667\n",
      "Execute when no exceptions were raised \n",
      "Errore Hand,ig the block\n",
      "it will execute in any situations \n",
      "Error: Birth year is in the future.\n"
     ]
    }
   ],
   "source": [
    "# Ans4 \n",
    "import logging\n",
    "\"\"\"\n",
    "try\n",
    "else\n",
    "finally \n",
    "raise\n",
    "\n",
    "\"\"\"\n",
    "# 1 try \n",
    "\"\"\"\n",
    "The try statement is used to enclose a block of code that may raise an exception.\n",
    "If an exception is raised within this block of code, control is transferred to the except statement.\n",
    "\"\"\"\n",
    "\n",
    "# 2 else  :\n",
    "\"\"\"\n",
    "The else statement is executed if no exceptions were raised in the try block. \n",
    "i;e there is no error inside the try block\n",
    "\"\"\"  \n",
    "# Example of try and  else  statement \n",
    "\n",
    "try:\n",
    "    logging.info(\" # block to raise an exception \") # uising the logging \n",
    "    res = 5/3\n",
    "    print(res)\n",
    "    \n",
    "except Exception as e :\n",
    "    #block that may handle exception \n",
    "    print(\"Errore Hand,ig the block\")\n",
    "else:\n",
    "    # code to be executed if no exceptions were raised\n",
    "    print(\"Execute when no exceptions were raised \")\n",
    "\n",
    "    \n",
    "# 3 finally:\n",
    "\n",
    "\"\"\"\n",
    "The finally statement is used to specify code that must be executed regardless of whether an exception was raised or no\n",
    "\"\"\"\n",
    "# Example of the finally \n",
    "\n",
    "\n",
    "try:\n",
    "    # block to raise an exception \n",
    "    res = 5/0\n",
    "    print(res)\n",
    "    \n",
    "except Exception as e :\n",
    "    logging.info(\" except block that may handle exception\") #using the logging\n",
    "    #block that may handle exception \n",
    "    print(\"Errore Hand,ig the block\")\n",
    "finally :\n",
    "    # code to be executed if no exceptions were raised\n",
    "    print(\"it will execute in any situations \")\n",
    "\n",
    "    \n",
    "# 4 raise\n",
    "\"\"\"\n",
    "The raise statement is used to raise an exception.  \n",
    "Basicaly it is an custom exception handling and rising\n",
    "\"\"\"\n",
    "\n",
    "# for example:\n",
    "\n",
    "def Validate_age(birth_year):\n",
    "    current_year = 2022\n",
    "    age = current_year - birth_year\n",
    "    if age < 0:\n",
    "        # raising the exception \n",
    "        raise ValueError(\"Birth year is in the future.\")\n",
    "    return age\n",
    "\n",
    "try:\n",
    "    \n",
    "    age = Validate_age(2030)\n",
    "except ValueError as e:\n",
    "    # handlig the exception\n",
    "    print(\"Error:\", e)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "02308c4f-870b-4a9a-8c43-9cc6465c1f38",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the Number to Check 55\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "correct ! Number is odd  \n"
     ]
    }
   ],
   "source": [
    "# Ans5\n",
    "# Custom Exceptions in python\n",
    "\n",
    "\"\"\"\n",
    "Custom exceptions in Python are user-defined exceptions that are raised in response to specific situations or errors that occur in a program. \n",
    "Custom exceptions are necessary because they provide a way to make a program respond in a specific way to errors or situations that are not covered by the built-in exceptions.\n",
    "\"\"\"\n",
    "# By creating the class and Using the raise keyword we raise the custom exceptions\n",
    "\n",
    "\"\"\"\n",
    "To create a custom exception, you can define a new class that inherits from the Exception class. The new class can have its own attributes and methods, but it should have a descriptive name that reflects the specific error or situation that it represents.\n",
    "\"\"\"\n",
    "\n",
    "# for using the logging \n",
    "\n",
    "import logging\n",
    "# For Example:\n",
    "class validate_number(Exception):\n",
    "    logging.basicConfig(filename = \"12feb.log\", level = logging.info ,format = '%(asctime)s %(message)s' )\n",
    "    logging.info(\" Creating the class \") #using the logging\n",
    "    \n",
    "    def __init__(self,num):\n",
    "        self.number= num\n",
    "        # function to chek odd even  and raise the exception\n",
    "        \n",
    "    def Number_check(Number):\n",
    "        if Number%2==0:\n",
    "            logging.info(\"using the raise keyword to raisse the exception\") #using the logging for further investigation\n",
    "            raise validate_number(\"Number is Even\")\n",
    "            \n",
    "        else:\n",
    "            logging.info(\"else work when there is no exception in try block\") #using the logging for further investigation\n",
    "            print(\"correct ! Number is odd  \")\n",
    "    \n",
    "    try:   \n",
    "        \n",
    "            Number = int(input(\"Enter the Number to Check\"))\n",
    "            Number_check(Number)\n",
    "            \n",
    "    except Exception as e:\n",
    "        logging.info(\"exception is handled here \")\n",
    "        print(e)\n",
    "        \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8dcec1b3-cc6c-4d91-8444-c964fa9907e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ans6\n",
    "\"\"\"\n",
    " we are creating a custom class to handle the excption \n",
    " \"\"\"\n",
    "\n",
    "# for Example \n",
    "\n",
    "import logging\n",
    "# For Example:\n",
    "class validate_number(Exception):\n",
    "    logging.basicConfig(filename = \"12feb.log\", level = logging.info ,format = '%(asctime)s %(message)s' )\n",
    "    logging.info(\" Creating the class \") #using the logging\n",
    "    \n",
    "    def __init__(self,num):\n",
    "        self.number= num\n",
    "        # function to chek odd even  and raise the exception\n",
    "        \n",
    "    def Number_check(Number):\n",
    "        if Number%2==0:\n",
    "            logging.info(\"using the raise keyword to raisse the exception\") #using the logging for further investigation\n",
    "            raise validate_number(\"Number is Even\")\n",
    "            \n",
    "        else:\n",
    "            print(\"correct ! Number is odd  \")\n",
    "    \n",
    "    try:   \n",
    "            logging.info(\"exception is riased here in try block\") #using the logging for further investigation\n",
    "            Number = int(input(\"Enter the Number to Check\"))\n",
    "            Number_check(Number)\n",
    "            \n",
    "    except Exception as e:\n",
    "        logging.info(\"exception is handled here \")\n",
    "        print(e)\n",
    "        "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
